<Project Sdk="Microsoft.NET.Sdk.Razor">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<PackageId>TruePeople.SharePreview</PackageId>
		<Title>TruePeople SharePreview</Title>
		<Description>Share preview URLs with non-Umbraco users!</Description>
		<RootNamespace>TruePeople.SharePreview</RootNamespace>
		<StaticWebAssetBasePath>App_Plugins/TruePeopleSharePreview</StaticWebAssetBasePath>
		<PackageReleaseNotes>Updated to modern Umbraco v13 packaging approach</PackageReleaseNotes>
	</PropertyGroup>

	<ItemGroup>
		<None Include="build\**\*.*">
			<Pack>True</Pack>
			<PackagePath>buildTransitive</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Umbraco.Cms.Web.BackOffice" Version="13.10.0" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="wwwroot\backoffice\shareablepreview\settings.html" />
	  <None Include="wwwroot\backoffice\shareablepreview\sharepreview-settings.controller.js" />
	  <None Include="wwwroot\components\multi-share-link.html" />
	  <None Include="wwwroot\components\multisharelink.directive.js" />
	  <None Include="wwwroot\components\single-share-link.html" />
	  <None Include="wwwroot\components\singlesharelink.directive.js" />
	  <None Include="wwwroot\css\main.css" />
	  <None Include="wwwroot\js\sharepreview.copy.service.js" />
	  <None Include="wwwroot\js\sharepreview.resource.js" />
	  <None Include="wwwroot\js\sharepreview.service.js" />
	  <None Include="wwwroot\lang\en-US.xml" />
	  <None Include="wwwroot\lang\nl-NL.xml" />
	  <None Include="wwwroot\overlays\multiple-variants-overlay.controller.js" />
	  <None Include="wwwroot\overlays\multiple-variants-sharepreview-overlay.html" />
	  <None Include="wwwroot\package.manifest" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="App_Plugins\" />
	</ItemGroup>
</Project>